# Generated by Django 4.1.7 on 2023-05-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_alumno_fecha_nacimiento_alter_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.CreateModel(
            name='Detalle_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('mail_alternativo', models.EmailField(max_length=128, verbose_name='Mail Alternativo')),
                ('telefono_alternativo', models.IntegerField(max_length=10, verbose_name='Teléfono alternativo')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.alumno')),
            ],
        ),
    ]
