# Generated by Django 4.1.7 on 2023-05-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_remove_alumno_fecha_nacimiento_detalle_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=128, verbose_name='Apellido')),
                ('mail', models.EmailField(max_length=128, verbose_name='Mail')),
                ('dni', models.CharField(max_length=8, null=True, verbose_name='DNI')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalle_alumno',
            name='id',
        ),
        migrations.AlterField(
            model_name='detalle_alumno',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula_virtual.alumno'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.IntegerField(max_length=4, verbose_name='Número de comisión')),
                ('alumnos', models.ManyToManyField(to='aula_virtual.alumno')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.instructor')),
            ],
        ),
    ]
