# Generated by Django 4.1.7 on 2023-05-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0004_instructor_remove_detalle_alumno_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(max_length=100, null=True, verbose_name='Legajo'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cuit',
            field=models.CharField(max_length=100, null=True, verbose_name='Cuit'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='comision',
            field=models.IntegerField(verbose_name='Número de comisión'),
        ),
        migrations.AlterField(
            model_name='detalle_alumno',
            name='telefono_alternativo',
            field=models.IntegerField(verbose_name='Teléfono alternativo'),
        ),
    ]
